### ISSUE TITLE
[Reimplementation] How to get code of model's structure?

### ISSUE THREAD

**Issue by zzuzs** [shaunyuan22/CFINet#11]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmdetection/issues) and [Discussions](https://github.com/open-mmlab/mmdetection/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmdetection) or [latest version (3.x)](https://github.com/open-mmlab/mmdetection/tree/dev-3.x).

### 💬 Describe the reimplementation questions

I want to understand and learn the structure of the model. Is the model code under CFINet? But there is no code after downloading.

### Environment

No problem

### Expected results

code

### Additional information

NO

**Comment by shaunyuan22** [comment]
The `CFINet` folder is unsed in this repo. The implementation of CFINet please refer to the follow:
crpn: `mmdet/models/dense_heads/crpn_head.py`
fi_head: `mmdet/models/roi_heads/feature_imitation_roi_head.py`

Moreover, the config of CFINet is in `configs/cfinet`.
