### ISSUE TITLE
[Docs] 我想知道您们的推理速度如何

### ISSUE THREAD

**Issue by sjz-hub** [shaunyuan22/CFINet#12]
### Branch

master branch  https://mmdetection.readthedocs.io/en/latest/

### 📚 The doc issue

请问最近您们是否和最新的单阶段目标检测yolov8对比过推理速度的差异。

**Comment by shaunyuan22** [comment]
nope, generally speaking, one-stage detectors enjoy speed advantages over two-stage counterparts
