### ISSUE TITLE
python ./tools/test.py ${CONFIG_FILE} ${WORK_DIR} --eval bbox中的${CONFIG_FILE} ${WORK_DIR}参数选择

### ISSUE THREAD

**Issue by yaosx425** [shaunyuan22/CFINet#13]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmdetection/issues) and [Discussions](https://github.com/open-mmlab/mmdetection/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmdetection) or [latest version (3.x)](https://github.com/open-mmlab/mmdetection/tree/dev-3.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

master branch https://github.com/open-mmlab/mmdetection

### Environment

sys.platform: linux
Python: 3.8.18 (default, Sep 11 2023, 13:40:15) [GCC 11.2.0]
CUDA available: True
GPU 0,1,2,3,4,5,6,7: NVIDIA GeForce RTX 3080 Ti
CUDA_HOME: /usr/local/cuda-11.2
NVCC: Cuda compilation tools, release 11.2, V11.2.67
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.11.0+cu113
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.5.2 (Git Hash a9302535553c73243c632ad3c4c80beec3d19a1e)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.3
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.2
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.2.0, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.11.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=OFF, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF,

TorchVision: 0.12.0+cu113
OpenCV: 4.8.1
MMCV: 1.5.0
MMCV Compiler: GCC 7.5
MMCV CUDA Compiler: 11.2
MMDetection: 2.26.0+f365b8d

### Reproduces the problem - code sample

![1702261523949](https://github.com/shaunyuan22/CFINet/assets/142800903/b3ad27d2-49ed-496b-8681-e2f32cec16a0)

### Reproduces the problem - command or script

Traceback (most recent call last):
  File "/data2/shuxuan_anaconda/envs/cfinet/lib/python3.8/site-packages/mmcv/utils/registry.py", line 52, in build_from_cfg
    return obj_cls(**args)
  File "/data2/shuxuan_anaconda/envs/cfinet/lib/python3.8/site-packages/mmdet/datasets/custom.py", line 97, in __init__
    self.data_infos = self.load_annotations(local_path)
  File "/data2/shuxuan_anaconda/envs/cfinet/lib/python3.8/site-packages/mmdet/datasets/coco.py",  line 72, in load_annotations
    self.coco = COCO(ann_file)
  File "/data2/shuxuan_anaconda/envs/cfinet/lib/python3.8/site-packages/mmdet/datasets/api_wrappers/coco_api.py", line 23, in __init__
    super().__init__(annotation_file=annotation_file)
  File "/data2/shuxuan_anaconda/envs/cfinet/lib/python3.8/site-packages/pycocotools/coco.py", line 81, in __init__
    with open(annotation_file, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'data/coco/annotations/instances_val2017.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./tools/test.py", line 286, in <module>
    main()
  File "./tools/test.py", line 217, in main
    dataset = build_dataset(cfg.data.test)
  File "/data2/shuxuan_anaconda/envs/cfinet/lib/python3.8/site-packages/mmdet/datasets/builder.py ", line 82, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "/data2/shuxuan_anaconda/envs/cfinet/lib/python3.8/site-packages/mmcv/utils/registry.py",  line 55, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
FileNotFoundError: CocoDataset: [Errno 2] No such file or directory: 'data/coco/annotations/instances_val2017.json'
不知道是不是mmcv没有配置好

### Reproduces the problem - error message

其中显示没有这个数据，但是您给的数据集里面没有那个标记文件，不知道是不是我选择的configs有问题，如果要测试SODA-D这个数据集的话，我应该选择哪个configs配置文件呢？

### Additional information

SODA-D

**Comment by shaunyuan22** [comment]
`No such file or directory: 'data/coco/annotations/instances_val2017.json`, 你这个json文件是COCO数据集的。我不太理解你是要跑CFINet还是在SODA-D数据集上跑其他模型

**Comment by yaosx425** [comment]
> `No such file or directory: 'data/coco/annotations/instances_val2017.json`, 你这个json文件是COCO数据集的。我不太理解你是要跑CFINet还是在SODA-D数据集上跑其他模型

同学 你好！！我是想跑CFINet 用SODA-D的数据集 ，但是我下载了数据集应该放在什么目录里呢？现在报错 No such file or directory: '/data/SODA-D/divData/Annotations/test.json'

**Comment by shaunyuan22** [comment]
请按照[此链接](https://github.com/shaunyuan22/CFINet/tree/master/tools/img_split)完成SODA-D数据集的数据准备工作，然后按照本项目的readme运行即可，我猜您对MMDetection并不熟悉，建议您移步[这里](https://github.com/open-mmlab/mmdetection)查看官方文档，本项目使用的是mmdet-2.26.0

**Comment by yaosx425** [comment]
> 请按照[此链接](https://github.com/shaunyuan22/CFINet/tree/master/tools/img_split)完成SODA-D数据集的数据准备工作，然后按照本项目的readme运行即可，我猜您对MMDetection并不熟悉，建议您移步[这里](https://github.com/open-mmlab/mmdetection)查看官方文档，本项目使用的是mmdet-2.26.0

好的！！谢谢！！我继续学习一下！！
