### ISSUE TITLE
[Reimplementation] 我完全按照你的数据集合代码复现

### ISSUE THREAD

**Issue by sjz-hub** [shaunyuan22/CFINet#14]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmdetection/issues) and [Discussions](https://github.com/open-mmlab/mmdetection/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmdetection) or [latest version (3.x)](https://github.com/open-mmlab/mmdetection/tree/dev-3.x).

### 💬 Describe the reimplementation questions

自己在SODA-D数据集上训练的结果loss比作者提供的日志文件高，但是AP效果反而比作者的好

### Environment

2080Ti
batch 2

### Expected results

![image](https://github.com/shaunyuan22/CFINet/assets/64513299/79a9fa77-171e-4714-a468-cb924158c4dd)
发现我的loss比你的高，但是最后的AP结果反而比你好，感觉很费解，你在代码中是否设置了随机种子，当然我的batch改为2，按照我的理解，作者你的最后结果应该是取你所有实验中最好的结果，为啥我一次实验看着的最后的结果比你的结果好呢，比较费解

**Comment by yaosx425** [comment]
同学你好！想请教一下，你跑的SODA-D数据集的权重是自己训练的吗？测试的指令是怎么写的呀？

**Comment by shaunyuan22** [comment]
The results are reported on the SODA-D test-set instead of the val-set.

**Comment by yaosx425** [comment]
> The results are reported on the SODA-D test-set instead of the val-set.

同学你好！！我想问下 cfinet数据集应该放在哪里呀 我放在主目录 但是报错 FileNotFoundError: SODADDataset: [Errno 2] No such file or directory: '/data/SODA-D/divData/Annotations/test.json'

**Comment by yaosx425** [comment]
> > 同学你好！想请教一下，你跑的SODA-D数据集的权重是自己训练的吗？测试的指令是怎么写的呀？
> 
> 是的，测试的指令就在作者的readme上，只需要将自己训练出来的模型替换第二个参数即可

好的！！谢谢同学 我知道了

**Comment by runhuzhao** [comment]
你好，我想问一下数据集val和test是怎么分割的，和train的方式一样吗

**Comment by shaunyuan22** [comment]
> 你好，我想问一下数据集val和test是怎么分割的，和train的方式一样吗
完全一致

**Comment by shaunyuan22** [comment]
@runhuzhao train, val和test的分割方式完全一致，区别只在于数据

**Comment by runhuzhao** [comment]
> @runhuzhao train, val和test的分割方式完全一致，区别只在于数据

谢谢，我尝试了一下，在test上的AP达到了60.7。最后，如果说我想对整张图片进行推理并可视化，那么也需要进行分割后推理，再对推理结果进行拼接吗。

**Comment by shaunyuan22** [comment]
对的，先对检测结果进行merge，然后在原图也就是未裁剪的图上进行可视化

**Comment by runhuzhao** [comment]
> 对的，先对检测结果进行merge，然后在原图也就是未裁剪的图上进行可视化

好的，感谢！

**Comment by LW091** [comment]
> > 对的，先对检测结果进行merge，然后在原图也就是未裁剪的图上进行可视化
> 
> 好的，感谢！

你好，请问你是如何对检测结果进行merge的呢？

**Comment by runhuzhao** [comment]
> > > 对的，先对检测结果进行merge，然后在原图也就是未裁剪的图上进行可视化
> > 
> > 
> > 好的，感谢！
> 
> 你好，请问你是如何对检测结果进行merge的呢？

其实merge的代码已经有了，在mmdet/datasets/sodad.py 中作者重写了评估的方法以及对检测结果进行merge的方法

**Comment by LW091** [comment]
好的谢啦





---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月26日(周日) 中午1:31
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [shaunyuan22/CFINet] [Reimplementation] 我完全按照你的数据集合代码复现 (Issue #14)




    
对的，先对检测结果进行merge，然后在原图也就是未裁剪的图上进行可视化
  
好的，感谢！
  
你好，请问你是如何对检测结果进行merge的呢？
  
其实merge的代码已经有了，在mmdet/datasets/sodad.py 中作者重写了评估的方法以及对检测结果进行merge的方法
