### ISSUE TITLE
[Docs] 关于数据集准备的一些疑问

### ISSUE THREAD

**Issue by forgivehat** [shaunyuan22/CFINet#15]
### Branch

master branch  https://mmdetection.readthedocs.io/en/latest/

### 📚 The doc issue

在img_split的文档里，处理SODA-D数据集的时候用到了以下命令：
`python tools/img_split/sodad_split.py --cfgJson sodad_train.json `，但在项目里并没有找到sodad_train.json，只有一个类似的split_train.sjon，请问这里是不是有笔误？
另外，在img_split/split_config目录下只有split_train.json，我仿照split_train的格式创建了split_test.json和split_val.json，然后分别运行分割脚本，处理后的数据也放到了/data/SODA-D/divData/目录下。随后我执行训练脚本时仍然会提示No such file or directory: '/data/SODA-D/rawData/Annotations/val_wo_ignore.json'，所以这三个xxx_ignore.json应该如何得到呢？

**Comment by shaunyuan22** [comment]
1. You need to modify the split json config by yourself.
2. `train_wo_ignore.json` can  be obtained by filtering the `ignore` annotations in `train.json`, likewise for `val_wo_ignore.json` and `test_wo_ignore.json`

**Comment by yaosx425** [comment]
> 1. You need to modify the split json config by yourself.
> 2. `train_wo_ignore.json` can  be obtained by filtering the `ignore` annotations in `train.json`, likewise for `val_wo_ignore.json` and `test_wo_ignore.json` . We've updated the code and please refer to [here](https://github.com/shaunyuan22/SODA-mmdetection/blob/master/tools/img_split/generate_wo_ignore.py).

同学你好！！！我测试了您的模型，跑通了代码，然后对图片进行检测，测试发现对于小目标检测性能非常好，然后我想测试一下大目标，然后就类似的放了一张图片，图片里面只有一辆车，发现检测不出，所以想请问一下您，这个模型是仅适用于小目标吗？

**Comment by shaunyuan22** [comment]
The proposed CFINet and SODA dataset are tailored for Small Object Detection, and large-scale objects can be handled well by almost all the mainstream detectors, hence this is not our  consideration. Moreover, that's why we ignore the instances with an area larger than 2000 pixels in SODA dataset.

**Comment by yaosx425** [comment]
> The proposed CFINet and SODA dataset are tailored for Small Object Detection, and large-scale objects can be handled well by almost all the mainstream detectors, hence this is not our consideration. Moreover, that's why we ignore the instances with an area larger than 2000 pixels in SODA dataset.

Okay, I've understood.thank you for your reply！！!
