### ISSUE TITLE
数据集问题

### ISSUE THREAD

**Issue by yumu-173** [shaunyuan22/CFINet#16]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmdetection/issues) and [Discussions](https://github.com/open-mmlab/mmdetection/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmdetection) or [latest version (3.x)](https://github.com/open-mmlab/mmdetection/tree/dev-3.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

master branch https://github.com/open-mmlab/mmdetection

### Environment

torch1.10.0
mmcv-full 1.3.17

### Reproduces the problem - code sample

 if ann.get('iscrowd', False):
                gt_bboxes_ignore.append(bbox)
            else:
                gt_bboxes.append(bbox)
                gt_labels.append(self.cat2label[ann['category_id']])
                gt_masks_ann.append(ann['segmentation'])

### Reproduces the problem - command or script

bash tools/dist_train.sh

### Reproduces the problem - error message

当我运行dist_train.sh脚本时，需要rawData中的*_wo_ignore.json并且在读取注释json的过程中还需要注释的segmentation，这些是SODA数据集中没有提供的，并且因为训练过程比较长，想请问是否可以提供预训练的脚本，可以直接进行test

### Additional information

1、更全面的注释文件
2、预训练模型

**Comment by shaunyuan22** [comment]
1. `train_wo_ignore.json` can  be obtained by filtering the `ignore` annotations in `train.json`, likewise for `val_wo_ignore.json` and `test_wo_ignore.json` .
 2. `segmentation` will **NOT** be used in training detection models, namely you don't have to load `gt_masks` during loading SODA-D data, please check your training config.
 3. We provide the specific configs for benckmarking models in our paper please refer to [SODA-mmdet](https://github.com/shaunyuan22/SODA-mmdetection) and [SODA-mmrot](https://github.com/shaunyuan22/SODA-mmrotate). Releasing the pretrained models is not in our near-term plans and your understanding is much appreciated.
