### ISSUE TITLE
[New Dataset] 请问您在coco数据集上进行过实验么？

### ISSUE THREAD

**Issue by mxyyy1002** [shaunyuan22/CFINet#19]
### Model/Dataset/Scheduler description

![2024-01-16 10-56-13屏幕截图](https://github.com/shaunyuan22/CFINet/assets/110209256/5c07614c-19b4-4b64-9f61-5f87213e9cff)
在coco数据集上进行实验，报错这个，是因为数据集问题么

### Open source status

- [ ] The model implementation is available
- [ ] The model weights are available.

**Comment by shaunyuan22** [comment]
No, all the experiments are based on SODA benchmark. I'm not sure whether dataset setups trigger this error based on current information

**Comment by Bian-jh** [comment]
> ### Model/Dataset/Scheduler description
> 
> ![2024-01-16 10-56-13屏幕截图](https://private-user-images.githubusercontent.com/110209256/296919054-5c07614c-19b4-4b64-9f61-5f87213e9cff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4MDE2ODgsIm5iZiI6MTcyODgwMTM4OCwicGF0aCI6Ii8xMTAyMDkyNTYvMjk2OTE5MDU0LTVjMDc2MTRjLTE5YjQtNGI2NC05ZjYxLTVmODcyMTNlOWNmZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxM1QwNjM2MjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YzE4MDRkOGYxZjljNjgwM2VmZjgyMDhlNDk5NGQwNTAwNTIwN2EzZjBjMThjNmU3MjgxZjM4ZGM5ODEwNmUzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.e0sblIPzqGKszf4xVb1RaMRz91J9vsEvCVaJI7TxEos) 在coco数据集上进行实验，报错这个，是因为数据集问题么
> ### Open source status
> 
>     * [ ]  The model implementation is available
> 
>     * [ ]  The model weights are available.
> 
> 
> ### Provide useful links for the implementation
> 
> _No response_

Hello, have you tackled this problem?
