### ISSUE TITLE
[CFINet] 文件夹打不开 下载下来也是空文件夹

### ISSUE THREAD

**Issue by Hiyuur** [shaunyuan22/CFINet#20]
### Branch

master branch  https://mmdetection.readthedocs.io/en/latest/

### 📚 The doc issue

CFINet]文件夹打不开 ，麻烦请看看是怎么回事

**Comment by shaunyuan22** [comment]
是项目的matser文件夹打不开，还是项目根目录的CFINet文件夹打不开？
后者不影响代码使用
