### ISSUE TITLE
[Docs] 请问为什么SODA-D jason注释文件里为什么没有iscrowd键

### ISSUE THREAD

**Issue by Hiyuur** [shaunyuan22/CFINet#21]
### Branch

master branch  https://mmdetection.readthedocs.io/en/latest/

### 📚 The doc issue

请问为什么SODA-D jason注释文件里为什么没有iscrowd键，mmdetection3.x会报错。一般coco格式的数据集都会有这个键吧
感谢回答

**Comment by shaunyuan22** [comment]
iscrowd在我们的小目标数据集中没有意义，所以并未包含此键
