### ISSUE TITLE
框架

### ISSUE THREAD

**Issue by zuikeaideren** [shaunyuan22/CFINet#23]
您好，我的框架是detectron2，和您的框架不同，我想把您的代码放到我的框架中，我应该主要看rpn_had和feature_imitation_roi_head这两个代码吗？谢谢您的回答

**Comment by shaunyuan22** [comment]
主要涉及两部分代码，以及 [crpn_head](https://github.com/shaunyuan22/CFINet/tree/master/mmdet/models/dense_heads)以及[feature_imitation_roi_head](https://github.com/shaunyuan22/CFINet/blob/master/mmdet/models/roi_heads/feature_imitation_roi_head.py)。另外，样本分配策略部分请参考[dynamic_assigner](https://github.com/shaunyuan22/CFINet/blob/master/mmdet/core/bbox/assigners/dynamic_assigner.py)
