### ISSUE TITLE
num_base_anchors的值大于1时报错

### ISSUE THREAD

**Issue by Renalyn-pan** [shaunyuan22/CFINet#24]
当我将anchor_generator中每个锚点生成的锚框设置为3时([0.5, 1.0, 1.5])，在dynamic_assigner中进行assign_wrt_overlaps操作时，在更新最低阈值时会报错inds和potential_low_thr的维度不匹配：
`IndexError: The shape of the mask [87296] at index 0 does not match the shape of the indexed tensor [261888] at index 0`
对应报错代码：
`for i in range(num_gts):   
            inds = (anchor_argmax_overlaps == i) & \
                   (anchor_max_overlaps >= gt_pos_thrs[i])
            potential_low_thr[inds] = gt_pos_thrs[i] `
请问这个应该怎么修改呢？

**Comment by shaunyuan22** [comment]
`num_base_anchors`大于1时，后边的feature adaption没法进行的，因为一个特征点只能对应一对偏移量`(delta_x, delta_y)`

**Comment by Renalyn-pan** [comment]
那用于SODA-A遥感中也是只一个特征点设置一个偏移的框是吗，因为普通都是会设置三个长宽比的框



---原始邮件---
发件人: "Shaun ***@***.***&gt;
发送时间: 2024年3月23日(周六) 晚上10:01
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [shaunyuan22/CFINet] num_base_anchors的值大于1时报错 (Issue #24)




 
num_base_anchors大于1时，后边的feature adaption没法进行的，因为一个特征点只能对应一对偏移量(delta_x, delta_y)

**Comment by shaunyuan22** [comment]
是的，与Cascade RPN保持一致在每个点只放置一个anchor
