### ISSUE TITLE
关于Feat2Embed Module

### ISSUE THREAD

**Issue by Eason1337** [shaunyuan22/CFINet#27]
你好！！谢谢你这么好的工作。

关于Feat2Embed Module，我一直在困惑该如何解释经过这个module（类似于降低维度）以后，和直接用原始特征相比较这样学习有什么好处呢？如果方便的话能否解答一下我的困惑，感激不尽！

**Comment by shaunyuan22** [comment]
谢谢您对我们工作的关注。
Feat2Embed的设计初衷主要有两个：
1. 在进行对比学习前，需要将原始特征进行flatten，直接暴力地将7*7*256的原始特征flatten当然也能够完成后续运算，但会打乱ROI的结构信息，所以使用Feat2Embed获得区域的compact representation；
2. 直接对原始特征进行对比学习可能会丢失每个实例本身特有的信息

**Comment by Eason1337** [comment]
谢谢作者的回答！！对我很有帮助！！再次感谢！
