### ISSUE TITLE
Reimplementation, Model config documents

### ISSUE THREAD

**Issue by Qqhjkl** [shaunyuan22/CFINet#31]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmdetection/issues) and [Discussions](https://github.com/open-mmlab/mmdetection/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmdetection) or [latest version (3.x)](https://github.com/open-mmlab/mmdetection/tree/dev-3.x).

### 💬 Describe the reimplementation questions

Hello, I would like to run your model, is there a config file in the code that adapts to the SODA dataset?

### Environment

I'm not experiencing environment configuration related issues.

**Comment by shaunyuan22** [comment]
configs for CFINet on the SODA-D dataset please see [here](https://github.com/shaunyuan22/CFINet/tree/master/configs/cfinet)
