### ISSUE TITLE
[New Models] Problem loading dataset

### ISSUE THREAD

**Issue by Alexwong-1024** [shaunyuan22/CFINet#8]
### Model/Dataset/Scheduler description

Hello author, I want to use the soda-a data set for training, but your CFINet file only loads CFINet/configs/_base_/datasets/sodad.py data. Does the soda-a data set also use this sodad.py? ? The reply you are looking forward to!

### Open source status

- [ ] The model implementation is available
- [ ] The model weights are available.

**Comment by shaunyuan22** [comment]
Please find more details about using SODA-A dataset from this [url](https://github.com/shaunyuan22/SODA-mmrotate)

**Comment by Alexwong-1024** [comment]
> Please find more details about using SODA-A dataset from this [url](https://github.com/shaunyuan22/SODA-mmrotate)

Thanks for your reply, I'll give it a try and wish you a happy life!

**Comment by ZachL1** [comment]
> Please find more details about using SODA-A dataset from this [url](https://github.com/shaunyuan22/SODA-mmrotate)

The SODA-mmrotate repository you mentioned seems to only contain preprocessing scripts, the rest is not clear.

So is it possible to share the configuration file about the SODA-A dataset? 
Or maybe it has exactly the same `train_pipeline` and `test_pipeline` as SODA-D? Once we organize SODA-A in the same format as SODA-D, can we just use `configs/_base_/datasets/sodad.py`? (Possibly with a simple path change)

If so or if not, please let us know. Much appreciated!

**Comment by Alexwong-1024** [comment]
@ZachL1 I think if we convert the annotation format of SODA-A dataset to SODA-D annotation format, it should not be very effective in training the model because SODA-A dataset is rotated type, that's my personal opinion, and could you please tell me if you can use SODA-A dataset to train CFINet? If yes, can you share how to configure it? I will be grateful.

**Comment by shaunyuan22** [comment]
If you guys try to run CFINet on the SODA-A dataset, the whole thing you need to do is transfering the codes in here to mmrot fashion as i stated in #10 , which won't take too long. And the data preparation of SODA-A dataset please refer to [here](https://github.com/shaunyuan22/SODA-mmrotate). 
In other words, you don't need to deal with the data pipeline of SODA-A dataset, we've provided the whole thing.
