### ISSUE TITLE
[Feature] Pre-trained model on the SODA.

### ISSUE THREAD

**Issue by ZachL1** [shaunyuan22/CFINet#9]
### What's the feature?

Great work!

Is it possible to share your pre-trained model on the SODA dataset?

**Comment by shaunyuan22** [comment]
sry this is not in our near-term plans and you can traing the model according to our codes

**Comment by shaunyuan22** [comment]
A trained model of CFINet is available at [here](https://drive.google.com/drive/u/0/folders/1ZIng20MdvEoH5F73z3wZM08weLpUviOv), and its evaluation result is as follow. Hope this could help you
```
+-------+-------+-------+-------+-------+-------+-------+
|AP     |AP_50  |AP_75  |AP_eS  |AP_rS  |AP_gS  |AP_N   |
+-------+-------+-------+-------+-------+-------+-------+
|30.6   |60.5   |26.7   |14.6   |27.2   |36.4   |45.1   |
+-------+-------+-------+-------+-------+-------+-------+
```

```
+---------------+-------+----------------+-------+--------------+-------+
| category      | AP    | category       | AP    | category     | AP    |
+---------------+-------+----------------+-------+--------------+-------+
| people        | 0.375 | rider          | 0.189 | bicycle      | 0.140 |
| motor         | 0.256 | vehicle        | 0.463 | traffic-sign | 0.465 |
| traffic-light | 0.388 | traffic-camera | 0.147 | warning-cone | 0.327 |
+---------------+-------+----------------+-------+--------------+-------+

```

**Comment by ZachL1** [comment]
You are so kind, thank you for your reply! This helps me a lot!

By comparing the results of the paper, the trained model you provided should be trained on the SODA-D dataset, right? 

Would you consider providing models trained on SODA-A? I ran into a problem with SODA-A, which was the same as the existing issue #8, so I posted a comment there.

**Comment by Alexwong-1024** [comment]
Hello, can you use the SODA-A dataset for training on your end? @ZachL1

**Comment by ZachL1** [comment]
not yet. 
 I left it aside for now because, as you said, the SODA-A is a rotation type. This may not be what I want. I plan to try SODA-D first, and maybe I will pay attention to SODA-A when I have time in the future

Maybe @shaunyuan22 can make this clearer, such as creating a new branch in this repository focusing on SODA-A. It benefits the community and enhances the impact of this work, doesn’t it?
